version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: app/Dockerfile
    env_file:
      - ../.env
    restart: unless-stopped
    ports:
      - "80:8080"
    working_dir: /app
    volumes:
      - ../:/app
      - ../.dev/app/config/.rr.yaml:/etc/rr.yaml:ro