version: '3.9'

services:
  app:
    build:
      context: ./
      dockerfile: app/Dockerfile
    restart: unless-stopped
    ports:
      - "80:8080"
    working_dir: /api
    volumes:
      - ../:/api
      - ../.dev/app/config/.rr.yaml:/etc/rr.yaml:ro

  postgres:
    build:
      context: ./
      dockerfile: postgres/Dockerfile
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: main
    restart: unless-stopped
    ports:
      - "5432:5432"
    working_dir: /
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    build:
      context: ./
      dockerfile: mailhog/Dockerfile
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data: {}